CREATE TABLE `activities` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`type` enum('call','email','meeting','note','text','voicemail') NOT NULL,
	`direction` enum('inbound','outbound') DEFAULT 'outbound',
	`contactId` int,
	`propertyId` int,
	`listingId` int,
	`subject` varchar(300),
	`notes` text,
	`summary` text,
	`duration` int,
	`outcome` enum('reached','voicemail','no_answer','callback_requested','not_interested','interested','follow_up'),
	`occurredAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `activities_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `buyer_interests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`listingId` int NOT NULL,
	`contactId` int NOT NULL,
	`userId` int NOT NULL,
	`status` enum('prospect','contacted','interested','toured','loi_submitted','under_contract','closed','passed') NOT NULL DEFAULT 'prospect',
	`offerAmount` float,
	`notes` text,
	`lastContactedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `buyer_interests_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `contacts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`firstName` varchar(100) NOT NULL,
	`lastName` varchar(100) NOT NULL,
	`email` varchar(320),
	`phone` varchar(30),
	`company` varchar(200),
	`isOwner` boolean NOT NULL DEFAULT false,
	`isBuyer` boolean NOT NULL DEFAULT false,
	`buyerType` enum('individual','institutional','family_office','syndication','other'),
	`buyerCriteria` text,
	`ownerNotes` text,
	`address` text,
	`city` varchar(100),
	`state` varchar(50),
	`zip` varchar(20),
	`priority` enum('hot','warm','cold','inactive') NOT NULL DEFAULT 'warm',
	`tags` text,
	`notes` text,
	`lastContactedAt` timestamp,
	`nextFollowUpAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `contacts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `listings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`propertyId` int NOT NULL,
	`title` varchar(300) NOT NULL,
	`description` text,
	`askingPrice` float,
	`capRate` float,
	`noi` float,
	`status` enum('active','under_contract','sold','withdrawn') NOT NULL DEFAULT 'active',
	`listedAt` timestamp DEFAULT (now()),
	`closedAt` timestamp,
	`sellerId` int,
	`brokerNotes` text,
	`marketingMemo` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `listings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `notifications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`type` enum('buyer_interest','task_due','follow_up_overdue','contact_unreached','deal_update','system') NOT NULL,
	`title` varchar(300) NOT NULL,
	`message` text,
	`isRead` boolean NOT NULL DEFAULT false,
	`relatedContactId` int,
	`relatedPropertyId` int,
	`relatedListingId` int,
	`relatedTaskId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `notifications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `properties` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(200) NOT NULL,
	`propertyType` enum('mhc','apartment','self_storage','mixed') NOT NULL,
	`address` text,
	`city` varchar(100),
	`state` varchar(50) DEFAULT 'ID',
	`zip` varchar(20),
	`county` varchar(100),
	`unitCount` int,
	`vintageYear` int,
	`sizeSqft` int,
	`lotAcres` float,
	`estimatedValue` float,
	`lastSalePrice` float,
	`lastSaleDate` timestamp,
	`askingPrice` float,
	`capRate` float,
	`noi` float,
	`status` enum('tracking','prospect','contacted','negotiating','under_contract','sold','not_interested','listed') NOT NULL DEFAULT 'tracking',
	`ownerId` int,
	`ownerName` varchar(200),
	`latitude` float,
	`longitude` float,
	`notes` text,
	`tags` text,
	`lastContactedAt` timestamp,
	`nextFollowUpAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `properties_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `tasks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`title` varchar(300) NOT NULL,
	`description` text,
	`type` enum('call','email','meeting','follow_up','research','other') NOT NULL DEFAULT 'follow_up',
	`priority` enum('urgent','high','medium','low') NOT NULL DEFAULT 'medium',
	`status` enum('pending','in_progress','completed','cancelled') NOT NULL DEFAULT 'pending',
	`contactId` int,
	`propertyId` int,
	`listingId` int,
	`activityId` int,
	`dueAt` timestamp,
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `tasks_id` PRIMARY KEY(`id`)
);
