CREATE TABLE `buyer_criteria` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`contactId` int NOT NULL,
	`propertyTypes` text,
	`minUnits` int,
	`maxUnits` int,
	`minVintageYear` int,
	`maxVintageYear` int,
	`minPrice` float,
	`maxPrice` float,
	`markets` text,
	`states` text,
	`statuses` text,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `buyer_criteria_id` PRIMARY KEY(`id`),
	CONSTRAINT `buyer_criteria_contactId_unique` UNIQUE(`contactId`)
);
